Maybe mpich from source working?

diff --git a/.github/workflows/install-mpi.yml b/.github/workflows/install-mpi.yml
--- a/.github/workflows/install-mpi.yml
+++ b/.github/workflows/install-mpi.yml
@@ -28,8 +28,8 @@ jobs:
           #   version: "1.10.7"
           - lib: "mpich"
             version: "apt"
-          # - lib: "mpich"
-          #   version: "4.1.2"
+          - lib: "mpich"
+            version: "4.1.2"
           # - lib: "mpich"
           #   version: "4.1.2"
           # - lib: "mpich"
@@ -62,8 +62,6 @@ jobs:
       run: |
         # Note: using download.open-mpi.org as gh tags aren't pre configured
         MPI_VERISON_MAJOR_MINOR=$(cut -d '.' -f 1,2 <<< "${{ env.MPI_VERSION}}")
-        echo ${MPI_VERISON_MAJOR_MINOR}
-        echo $MPI_VERISON_MAJOR_MINOR
         echo "https://download.open-mpi.org/release/open-mpi/v${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz"
         wget -q https://download.open-mpi.org/release/open-mpi/v${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading OpenMPI '${{ env.MPI_VERSION }}'. Is it a valid version of OpenMPI?" && exit 1)
         tar -zxvf openmpi-${{ env.MPI_VERSION }}.tar.gz
@@ -75,14 +73,25 @@ jobs:
         echo "LD_LIBRARY_PATH=${{ runner.temp }}/mpi/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
         echo "LD_RUN_PATH=${{ runner.temp }}/mpi/lib:${LD_RUN_PATH}" >> $GITHUB_ENV
 
+    # This will only work for mpich >= 3.0, as 1.x is for mpich2 so requires handling differently
     # https://www.mpich.org/static/downloads/1.0.1/mpich2-1.0.1.tar.gz
     # https://www.mpich.org/static/downloads/4.1.2/mpich-4.1.2.tar.gz
     # https://www.mpich.org/static/downloads/3.0/mpich-3.0.tar.gz
     # https://www.mpich.org/static/downloads/3.1.2/mpich-3.1.2.tar.gz
-    # - name: Install MPICH from source
-    #   if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'mpich' }}
-    #   working-directory: ${{ runner.temp }}
-    #   run: |
+    - name: Install MPICH from source
+      if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'mpich' }}
+      working-directory: ${{ runner.temp }}
+      run: |
+        echo "https://www.mpich.org/static/downloads/${{ env.MPI_VERSION }}/mpich-${{ env.MPI_VERSION}}.tar.gz"
+        wget -q https://www.mpich.org/static/downloads/${{ env.MPI_VERSION }}/mpich-${{ env.MPI_VERSION}}.tar.gz --output-document mpich-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading MPICH '${{ env.MPI_VERSION }}'. Is it a valid version of MPICH?" && exit 1)
+        tar -zxvf mpich-${{ env.MPI_VERSION }}.tar.gz
+        cd mpich-${{ env.MPI_VERSION}}
+        ./configure --prefix="${{ runner.temp }}/mpi"
+        make -j `nproc`
+        make install -j `nproc`
+        echo "${{ runner.temp }}/mpi/bin" >> $GITHUB_PATH
+        echo "LD_LIBRARY_PATH=${{ runner.temp }}/mpi/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+        echo "LD_RUN_PATH=${{ runner.temp }}/mpi/lib:${LD_RUN_PATH}" >> $GITHUB_ENV
 
 
     - name: test
