testing

diff --git a/.github/workflows/install-mpi.yml b/.github/workflows/install-mpi.yml
--- a/.github/workflows/install-mpi.yml
+++ b/.github/workflows/install-mpi.yml
@@ -43,8 +43,10 @@ jobs:
       working-directory: ${{ runner.temp }}
       run: |
         # Note: using download.open-mpi.org as gh tags aren't pre configured
-        MPI_VERISON_MAJOR_MINOR=$(cut -d '.' -f 1,2 <<< "${{ env.MPI_VERSION}}") 
-        wget -q https://download.open-mpi.org/release/open-mpi/${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading OpenMPI ${{ env.MPI_VERSION }}. Is it a valid version of OpenMPI?" && exit 1)
+        MPI_VERISON_MAJOR_MINOR=$(cut -d '.' -f 1,2 <<< "${{ env.MPI_VERSION}}")
+        echo ${MPI_VERISON_MAJOR_MINOR}
+        echo $MPI_VERISON_MAJOR_MINOR
+        wget -q https://download.open-mpi.org/release/open-mpi/${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading OpenMPI '${{ env.MPI_VERSION }}'. Is it a valid version of OpenMPI?" && exit 1)
         tar -zxvf openmpi-${{ env.MPI_VERSION }}.tar.gz
         cd ompi-${{ env.MPI_VERSION}}
         ./configure --prefix="${{ runner.temp }}/mpi"
