switch to download.open-mpi.org

diff --git a/.github/workflows/install-mpi.yml b/.github/workflows/install-mpi.yml
--- a/.github/workflows/install-mpi.yml
+++ b/.github/workflows/install-mpi.yml
@@ -30,7 +30,7 @@ jobs:
       MPI_VERSION: ${{ matrix.mpi.version }}
 
     steps:
-    - uses: actions/checkout@v2
+    - uses: actions/checkout@v4
 
     - name: Install MPI from apt
       if: ${{ env.MPI_VERSION == 'apt' }}
@@ -42,12 +42,15 @@ jobs:
       if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'openmpi' }}
       working-directory: ${{ runner.temp }}
       run: |
-        wget -q https://github.com/open-mpi/ompi/archive/refs/tags/v${{ env.MPI_VERSION }}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "Error occured while downloading OpenMPI ${{ env.MPI_VERSION }}. Is it valid?" && exit 1)
+        # Note: using download.open-mpi.org as gh tags aren't pre configured
+        MPI_VERISON_MAJOR_MINOR=$(cut -d '.' -f 1,2 <<< "${{ env.MPI_VERSION}}") 
+        wget -q https://download.open-mpi.org/release/open-mpi/${MPI_VERISON_MAJOR_MINOR}/openmpi-${{ env.MPI_VERSION}}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || (echo "An Error occurred while downloading OpenMPI ${{ env.MPI_VERSION }}. Is it a valid version of OpenMPI?" && exit 1)
         tar -zxvf openmpi-${{ env.MPI_VERSION }}.tar.gz
         cd ompi-${{ env.MPI_VERSION}}
         ./configure --prefix="${{ runner.temp }}/mpi"
         make -j `nproc`
         make install -j `nproc`
+        which mpirun
 
     - name: test
       run: |
