Fixup

diff --git a/.github/workflows/install-mpi.yml b/.github/workflows/install-mpi.yml
--- a/.github/workflows/install-mpi.yml
+++ b/.github/workflows/install-mpi.yml
@@ -42,13 +42,8 @@ jobs:
       if: ${{ env.MPI_VERSION != 'apt' && env.MPI_LIB == 'openmpi' }}
       working-directory: ${{ runner.temp }}
       run: |
-        wget -q https://github.com/open-mpi/ompi/archive/refs/tags/v${{ env.MPI_VERSION }}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz
-        ls 
+        wget -q https://github.com/open-mpi/ompi/archive/refs/tags/v${{ env.MPI_VERSION }}.tar.gz --output-document openmpi-${{ env.MPI_VERSION }}.tar.gz || echo "Error occured while downloading OpenMPI ${{ env.MPI_VERSION }}. Is it valid?"
         tar -zxvf openmpi-${{ env.MPI_VERSION }}.tar.gz
-        ls
-        ls openmpi-${{ env.MPI_VERSION }}
-
-
 
     - name: test
       run: |
